#!/bin/bash
#SBATCH --account=fudenber_735
#SBATCH --partition=gpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=48GB
#SBATCH --time=3:59:00
#SBATCH --array=1

eval "$(conda shell.bash hook)"
conda activate openmm-env

python workflow.py
